### ISSUE TITLE
"Unsupported image file" errors

### ISSUE THREAD

**Issue by maxlath** [ShogunPanda/fastimage#2]
using `fastimage.info`, I get this kind of errors:

``` javascript
{ [FastImageError: Unsupported image file.]
  name: 'FastImageError',
  message: 'Unsupported image file.',
  url: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/%27Journey_to_the_Center_of_the_Earth%27_by_%C3%89douard_Riou_38.jpg',
  code: 'UNSUPPORTED_TYPE' }
```

it seems to be a perfectly valid image though, any clue on what could be wrong?

**Comment by ShogunPanda** [comment]
Sorry for the insanely long reply. I'll check it out soon.

**Comment by ShogunPanda** [comment]
Hi.
The problems seemed to be that the original cutoff threshold (4K) after which fastimage gave up were not enough for this URL.

To address it, you can completely disabled the feature by using `fastimage.threshold(-1)`. After this, the image will be downloaded up to the 100%, stopping as soon as it is identified.
Hope this helps!
  Shogun
