### ISSUE TITLE
I was already install 'fastimage' but when i run, i was get a error

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [ShogunPanda/fastimage#6]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/17617821/187345297-d7d39671-e253-4fd4-97c0-2ce2d5b6d43a.png">

**Comment by ShogunPanda** [comment]
Sorry for seeing this only now.
It seems to be a bundling error. Can you provide a reproducible repository somewhere so I can test this out?
